
name: Tests

on:
 - push
 
jobs:
    test:
     runs-on: ubuntu-lastest
     
     steps: 
       - uses: actions/checkout@v3
        
       - name: Setup Python

         uses: actions/setup-python@v4

         with: 
          python-version: '3.10'

       - name: Install Dependencies
         run: | 
           
            python -m pip install -upgrade pip

            pip install pytest-playwright

       - name: Ensure browsers are installd
        
         run: python -m playwright install chromimum --with-deps

       - name: Run Tests
         run: |
            cd cubeit
            python -m http.server 8000 &

            pytest -v 











